### ISSUE TITLE
Getters type generation not working.

### ISSUE THREAD

**Issue by y-temp4** [takefumi-yoshii/vuex-guardian#2]
Thank you for developing a useful library !

By the way, I found getters type generation not working in this case.

```js
getters: {
  count: (state) => state.count, // not working !
  count(state) {
    return state.count // working
  }
}
```

I would appreciate it if you could check it.

**Comment by takefumi-yoshii** [comment]
resolved at https://github.com/takefumi-yoshii/vuex-guardian/pull/3
